"""initial

Revision ID: b1024103bad2
Revises: 6fd92e15f7e6
Create Date: 2022-01-15 13:56:20.482141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1024103bad2'
down_revision = '6fd92e15f7e6'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
